from city import City

class Map():
    def __init__(self):
        self.initCities()
        self.addConnections()

    def initCities(self):
        self.Oradea = City("Oradea",380)
        self.Zerind = City("Zerind",374)
        self.Arad = City("Arad",366)
        self.Timisoara = City("Timisoara",329)
        self.Lugoj = City("Lugoj",244)
        self.Mehadia = City("Mehadia",241)
        self.Drobeta = City("Drobeta",242)
        self.Craiova = City("Craiova",160)
        self.Rimnicu = City("Rimnicu",193)
        self.Sibiu = City("Sibiu",253)
        self.Pitesi = City("Pitesi",100)
        self.Fagaras = City("Fagaras",176)
        self.Bucharest = City("Bucharest",0)
        self.Giurgiu = City("Giurgiu",77)
        self.Hirsova = City("Hirsova",151)
        self.Eforie = City("Eforie",161)
        self.Urziceni = City("Urziceni",80)
        self.Vaslui = City("Vaslui",199)
        self.Iasi = City("Iasi",226)
        self.Neamt = City("Neamt",234)

    def addConnections(self):
        self.Oradea.addconnection(self.Zerind, 71)
        self.Oradea.addconnection(self.Sibiu, 151)
        self.Zerind.addconnection(self.Oradea, 71)
        self.Zerind.addconnection(self.Arad, 75)
        self.Arad.addconnection(self.Sibiu, 140)
        self.Arad.addconnection(self.Zerind, 75)
        self.Arad.addconnection(self.Timisoara, 118)
        self.Timisoara.addconnection(self.Arad, 118)
        self.Timisoara.addconnection(self.Lugoj, 111)
        self.Lugoj.addconnection(self.Timisoara, 111)
        self.Lugoj.addconnection(self.Mehadia, 70)
        self.Mehadia.addconnection(self.Drobeta, 75)
        self.Mehadia.addconnection(self.Lugoj, 70)
        self.Drobeta.addconnection(self.Mehadia, 75)
        self.Drobeta.addconnection(self.Craiova, 120)
        self.Craiova.addconnection(self.Drobeta, 120)
        self.Craiova.addconnection(self.Rimnicu, 146)
        self.Craiova.addconnection(self.Pitesi, 120)
        self.Rimnicu.addconnection(self.Craiova, 146)
        self.Rimnicu.addconnection(self.Sibiu, 80)
        self.Rimnicu.addconnection(self.Pitesi, 97)
        self.Sibiu.addconnection(self.Arad, 140)
        self.Sibiu.addconnection(self.Oradea, 151)
        self.Sibiu.addconnection(self.Fagaras, 99)
        self.Sibiu.addconnection(self.Rimnicu, 80)
        self.Pitesi.addconnection(self.Craiova, 120)
        self.Pitesi.addconnection(self.Rimnicu, 97)
        self.Pitesi.addconnection(self.Bucharest, 101)
        self.Fagaras.addconnection(self.Sibiu, 99)
        self.Fagaras.addconnection(self.Bucharest, 211)
        self.Bucharest.addconnection(self.Fagaras, 211)
        self.Bucharest.addconnection(self.Pitesi, 101)
        self.Bucharest.addconnection(self.Giurgiu, 90)
        self.Bucharest.addconnection(self.Urziceni, 85)
        self.Giurgiu.addconnection(self.Bucharest, 90)
        self.Urziceni.addconnection(self.Hirsova, 98)
        self.Urziceni.addconnection(self.Bucharest, 85)
        self.Urziceni.addconnection(self.Vaslui, 142)
        self.Hirsova.addconnection(self.Eforie, 86)
        self.Hirsova.addconnection(self.Urziceni, 98)
        self.Eforie.addconnection(self.Hirsova, 86)
        self.Vaslui.addconnection(self.Urziceni, 142)
        self.Vaslui.addconnection(self.Iasi, 92)
        self.Iasi.addconnection(self.Vaslui, 92)
        self.Iasi.addconnection(self.Neamt, 87)
        self.Neamt.addconnection(self.Iasi, 87)